### PR TITLE
Feature/validation

### PR DESCRIPTION
**Pull request by Izebiafe**
- This is a continuation of the validation and spec PR. The previous PR was mistakenly closed so a revert on the last commit was made and a new PR was created from the previous PR and all required changes by the previous reviewer have been fully implemented.
- Please refer to Pull Request 3 to see the changes required.

### CODE REVIEW

**Review by fobadara — COMMENTED** [review]
Hi @Izebiafe, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

INVALID


## Invalid Code Review Request

You have submitted a project, that doesn't have a descriptive PR summary

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by fobadara — CHANGES_REQUESTED** [review]
Hi @Izebiafe, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

REDO

## Highlights
✅ Descriptive README
✅ Descriptive PR summary
✅ Clean code
✅ Good first attempt
✅ Good implementation of the principle of separating concerns.

## Required Changes ♻️
_Check the comments under the review._
I had to include some comments here because I can't make inline comments in all the affected files.
[REQUIRED] It is a requirement to test all the custom methods in the model files. Kindly write tests for `recentposts`.
[REQUIRED] In your post specs for the post model,  kindly write validation specs for the following: the presence and length of title, the numericality of comments and likes counter and whether they are positive or negative.
[REQUIRED] You are also required to test the `update_counter` and `recent_comment` custom methods in the post model.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ShadyShawkat — CHANGES_REQUESTED** [review]
## Hi @Izebiafe, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

Image

 ## Required Changes ♻️
- [ ] Kindly make sure to address the tests required by the previous reviewer, as your changes didn't add any new tests. The following are the tests you're to implement: 
   - [ ] [REQUIRED] It is a requirement to test all the custom methods in the model files. Kindly write tests for `recentposts`.
   - [ ] [REQUIRED] In your post specs for the post model, kindly write validation specs for the following: 
      - the presence and length of title.
      - the numericality of comments and likes counter and whether they are positive or negative.
   - [ ] [REQUIRED] You are also required to test the `update_counter` and `recent_comment` custom methods in the post model.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Strangeal — APPROVED** [review]
Hi @Izebiafe, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Alt Text

## Highlights
- Added test for custom methods, presence and length of title, and numericality of comments and likes counter,✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
